#!/bin/bash -f
# Vivado (TM) v2015.4 (64-bit)
#
# Filename    : pcie_a7_vivado.sh
# Simulator   : Cadence Incisive Enterprise Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Mar 24 22:39:09 +0100 2016
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015 
#
# usage: pcie_a7_vivado.sh [-help]
# usage: pcie_a7_vivado.sh [-lib_map_path]
# usage: pcie_a7_vivado.sh [-noclean_files]
# usage: pcie_a7_vivado.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'pcie_a7_vivado.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Script info
echo -e "pcie_a7_vivado.sh - Script generated by export_simulation (Vivado v2015.4 (64-bit)-id)\n"

# Script usage
usage()
{
  msg="Usage: pcie_a7_vivado.sh [-help]\n\
Usage: pcie_a7_vivado.sh [-lib_map_path]\n\
Usage: pcie_a7_vivado.sh [-reset_run]\n\
Usage: pcie_a7_vivado.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

if [[ ($# == 1 ) && ($1 != "-lib_map_path" && $1 != "-noclean_files" && $1 != "-reset_run" && $1 != "-help" && $1 != "-h") ]]; then
  echo -e "ERROR: Unknown option specified '$1' (type \"./pcie_a7_vivado.sh -help\" for more information)\n"
  exit 1
fi

if [[ ($1 == "-help" || $1 == "-h") ]]; then
  usage
fi

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./pcie_a7_vivado.sh -help\" for more information)\n"
        exit 1
      fi
      # precompiled simulation library directory path
     create_lib_mappings $2
     touch hdl.var
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
     touch hdl.var
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ncsim.key irun.key ncvlog.log ncvhdl.log compile.log elaborate.log simulate.log run.log waves.shm INCA_libs)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Main steps
run()
{
  setup $1 $2
  compile
  elaborate
  simulate
}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib)
  file="cds.lib"
  dir="ies"

  if [[ -e $file ]]; then
    rm -f $file
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path="<SPECIFY_COMPILED_LIB_PATH>"
  if [[ ($1 != "" && -e $1) ]]; then
    lib_map_path="$1"
  else
    echo -e "ERROR: Compiled simulation library directory path not specified or does not exist (type "./top.sh -help" for more information)\n"
  fi
  incl_ref="INCLUDE $lib_map_path/cds.lib"
  echo $incl_ref >> $file

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="DEFINE $lib $dir/$lib"
      echo $mapping >> $file
    fi
  done
}


# RUN_STEP: <compile>
compile()
{
  # Directory path for design sources and include directories (if any) wrt this path
  ref_dir="."
  # Command line options
  opts_ver="-64bit -messages -logfile ncvlog.log -append_log"
  opts_vhd="-64bit -V93 -RELAX -logfile ncvhdl.log -append_log"

  # Compile design files
  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_core_top.vhd" \

  ncvlog -work xil_defaultlib $opts_ver \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pipe_drp.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pipe_eq.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pipe_rate.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pipe_reset.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pipe_sync.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gtp_pipe_rate.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gtp_pipe_drp.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gtp_pipe_reset.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pipe_user.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pipe_wrapper.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_qpll_drp.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_qpll_reset.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_qpll_wrapper.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_rxeq_scan.v" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_axi_basic_rx_null_gen.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_axi_basic_rx_pipeline.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_axi_basic_rx.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_axi_basic_top.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_axi_basic_tx_pipeline.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_axi_basic_tx_thrtl_ctl.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_axi_basic_tx.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie_7x.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie_bram_7x.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie_bram_top_7x.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie_brams_7x.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie_pipe_lane.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie_pipe_misc.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie_pipe_pipeline.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gt_rx_valid_filter_7x.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gt_top.vhd" \

  ncvlog -work xil_defaultlib $opts_ver \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gt_wrapper.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gt_common.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gtp_cpllpd_ovrd.v" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_gtx_cpllpd_ovrd.v" \

  ncvhdl -work xil_defaultlib $opts_vhd \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie_top.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/source/pcie_a7_vivado_pcie2_top.vhd" \
    "$ref_dir/../../../ip/pcie_a7_vivado/sim/pcie_a7_vivado.vhd" \


  ncvlog $opts_ver -work xil_defaultlib \
    "glbl.v"

}

# RUN_STEP: <elaborate>
elaborate()
{
  opts="-64bit -relax -access +rwc -messages -logfile elaborate.log -timescale 1ps/1ps"
  libs="-libname unisims_ver -libname unimacro_ver -libname secureip -libname xil_defaultlib"
  ncelab $opts xil_defaultlib.pcie_a7_vivado xil_defaultlib.glbl $libs
}

# RUN_STEP: <simulate>
simulate()
{
  opts="-64bit -logfile simulate.log"
  ncsim $opts xil_defaultlib.pcie_a7_vivado -input simulate.do
}
# Script usage
usage()
{
  msg="Usage: pcie_a7_vivado.sh [-help]\n\
Usage: pcie_a7_vivado.sh [-lib_map_path]\n\
Usage: pcie_a7_vivado.sh [-reset_run]\n\
Usage: pcie_a7_vivado.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}


# Launch script
run $1 $2
